### ISSUE TITLE
Find all images and fonts needed

### ISSUE THREAD

**Issue by concolato** [USStateDept/search#333] opened 2016-09-07 19:37 UTC

**Comment by concolato** [comment] 2016-09-08 17:24
Planing to use Font Awesome: http://fontawesome.io/icons/#web-application

**Comment by brandtheisey** [comment] 2016-09-09 17:16
font awesome doesn't address the font portion of this issue.

**Comment by concolato** [comment] 2016-09-09 19:46
Then could you please tell me what does? I would think font-style: Ariel or something to that affect would do the trick. Am I wrong?

**Comment by brandtheisey** [comment] 2016-09-09 22:15
Font Awesome serves icons from a font-like file. Here is a Q&A with a FA developer that addresses this issue: https://www.impresspages.org/awesome-q-a-with-font-awesome-developer-dave-gandy

As to the second portion of your question, yes you can _suggest_ a font to a user but unless its downloaded onto their system what you get is up to the system and or the user. IE Helvetica can be wingdings or comic sans on a system if it isn't explicitly loaded by the website. So basically, if you want to guarantee a font appears as intended by the designer it must be downloaded. Here is an explanation in case I am not being clear: https://css-tricks.com/almanac/properties/f/font-family/

Since the question of what font was used in the demo wasn't asked until 12:45pm today, it is premature to close this issue. 

Additionally, since we have not, as of yet ID'd the font, we don't know if it requires any sort of LCCB-type paperwork to be downloaded on ON.

 For the task due on the 8th to be closable we need a list of any and all fonts required to make the search results page as shown in the powerpoint. 

For the task due today to be closable, the task on the 8th has to be closed.

**Closed as completed** 2016-09-15 22:36 UTC
